name: blaze-tactics # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Blaze Tactics
summary: Lead tactical fire teams in battle.
description: Assemble fiery teams and deploy strategic combat maneuvers to defeat enemy squads.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  blaze-tactics:
    command: bin/blaze-tactics-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  blaze-tactics:
    plugin: dump
    source: .
    organize:
      blaze-tactics-bin: bin/
